# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET localhost:8080/collection/twitter_json_01

###

POST localhost:8080/ksql
Accept: application/json
Content-Type: application/json

{
"ksql": "LIST TOPICS;"
}

###

POST localhost:8080/query HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "ksql": "SELECT * FROM twitter;",
  "streamsProperties": {
    "ksql.streams.auto.offset.reset": "earliest"
  }
}

###